export const Navbar = {
    FEED: 'FEED',
    RUNS_FEED: 'RUNS_FEED',
    CHATS: 'CHATS',
    PROFILE: 'PROFILE',
    NOTIFICATIONS: 'NOTIFICATIONS'
}

export const NotificationType = {
    CHAT_INVITATION: 'CHAT_INVITATION',
    MVP_VOTING: 'MVP_VOTING',
    RUN_NEARBY: 'RUN_NEARBY',
    FRIEND_REQUEST: 'FRIEND_REQUEST',
    POST_LIKE: 'POST_LIKE',
    POST_COMMENT: 'POST_COMMENT'
}